#!/bin/sh

if [ -d "$1" ];then
    echo "$1" is a directory
    exit
elif ! [ -f "$1" ]; then
    echo "$1": No such file
    exit
else
    bat "$1" --theme "gruvbox-dark" --decorations "never" || cat "$1"
fi
