#!/bin/sh

if [ "$1" = "ll" ]; then
    action=pull
elif [ "$1" = "clone" ]; then
    action=clone
else
    action=push
fi

remote() {
    if [ "$action" = "pull" ]; then
	git pull
    elif [ "$action" = "clone" ]; then
	git clone "$2"
    else
	git push
    fi
}

remote_retry() {
    time=1
    while [ "$time" -lt 11 ]
    do
	echo ">>> trying git $action $time time"
        if remote "$1" "$2"; then
	    return 0
	else
	    time=$((time + 1))
	fi
    done
    return 1
}

remote_retry "$1" "$2"
result=$?

if [ $result -eq 0 ]; then
    echo ">>> git $action finished, checking git status:" && git status
else
    echo ">>> git $action failed, checking git status:" && git status
fi

