#!/bin/sh

echo Hello "$(id -un)"!
time
honey
printf "\n"
awk '/^↓ /{ print }' /home/kate/.emacs.d/todo/a.todo
printf "\n"
awk '/^↑ /{ print }' /home/kate/.emacs.d/todo/a.todo
printf "\n"
awk '/^→ / { print }' /home/kate/.emacs.d/todo/a.todo
printf "\n"
awk '/^# / { print }' /home/kate/.emacs.d/todo/a.todo
pgrep clash > /dev/null || (plug && echo CLASH started at $(pgrep clash))
swapesc
