#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
    echo Hello "$(id -un)", you are @mac
    date
else
    echo Hello "$(id -un)", you are @gentoo
    time
    honey
    swapesc
fi

awk '/^---/{ print }' $HOME/.emacs.d/todo/todo.todo
awk '/^+++/{ print }' $HOME/.emacs.d/todo/todo.todo
awk '/^!!!/ { print }' $HOME/.emacs.d/todo/todo.todo
awk '/^###/ { print }' $HOME/.emacs.d/todo/todo.todo
